# Generated by Django 3.1.3 on 2021-03-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskaddress',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskaddress',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='status_to',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Ожидает подтверждение', 'Ожидает подтверждение'), ('Подтверждён', 'Подтверждён'), ('Исполнен', 'Исполнен')], max_length=21),
        ),
        migrations.AlterField(
            model_name='taskaddress',
            name='house',
            field=models.CharField(max_length=6),
        ),
    ]
