# Generated by Django 3.1.3 on 2021-04-01 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='profile',
            new_name='user',
        ),
    ]
