# Generated by Django 3.1.3 on 2021-05-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0003_auto_20210502_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='frozen_points',
            field=models.IntegerField(default=0),
        ),
    ]
